{
  "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/25693",
  "repository_url": "https://api.github.com/repos/ethereum/go-ethereum",
  "labels_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/25693/labels{/name}",
  "comments_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/25693/comments",
  "events_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/25693/events",
  "html_url": "https://github.com/ethereum/go-ethereum/issues/25693",
  "id": 1362999975,
  "node_id": "I_kwDOAOvK985RPbqn",
  "number": 25693,
  "title": "Clean sync Goerli broken(?) post merge on 1.10.21 and 1.10.23",
  "user": {
    "login": "ulope",
    "id": 55078,
    "node_id": "MDQ6VXNlcjU1MDc4",
    "avatar_url": "https://avatars.githubusercontent.com/u/55078?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/ulope",
    "html_url": "https://github.com/ulope",
    "followers_url": "https://api.github.com/users/ulope/followers",
    "following_url": "https://api.github.com/users/ulope/following{/other_user}",
    "gists_url": "https://api.github.com/users/ulope/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/ulope/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/ulope/subscriptions",
    "organizations_url": "https://api.github.com/users/ulope/orgs",
    "repos_url": "https://api.github.com/users/ulope/repos",
    "events_url": "https://api.github.com/users/ulope/events{/privacy}",
    "received_events_url": "https://api.github.com/users/ulope/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [
    {
      "id": 72233650,
      "node_id": "MDU6TGFiZWw3MjIzMzY1MA==",
      "url": "https://api.github.com/repos/ethereum/go-ethereum/labels/type:bug",
      "name": "type:bug",
      "color": "FF5E5E",
      "default": false,
      "description": ""
    },
    {
      "id": 1132754722,
      "node_id": "MDU6TGFiZWwxMTMyNzU0NzIy",
      "url": "https://api.github.com/repos/ethereum/go-ethereum/labels/need:more-information",
      "name": "need:more-information",
      "color": "db6fa3",
      "default": false,
      "description": ""
    }
  ],
  "state": "open",
  "locked": false,
  "assignee": null,
  "assignees": [

  ],
  "milestone": null,
  "comments": 3,
  "created_at": "2022-09-06T09:37:58Z",
  "updated_at": "2022-09-06T13:18:17Z",
  "closed_at": null,
  "author_association": "MEMBER",
  "active_lock_reason": null,
  "body": "#### System information\r\n\r\nGeth version: `v1.10.21` / `v1.10.23`\r\nOS & Version: Linux\r\n\r\n#### Expected behaviour\r\n\r\nA fresh sync from scratch of Goerli to work\r\n\r\n#### Actual behaviour\r\n\r\nDoes not work.\r\n- Geth `1.10.21`: \r\n  - Snap sync completes, afterwards State heal seems to continue indefinitely (aborted after 4 days)\r\n  - Last state heal log before abort:\r\n    `INFO [09-05|14:37:35.138] State heal in progress                   accounts=9@647.00B            slots=0@0.00B              codes=0@0.00B            nodes=16,319,436@8.09GiB   pending=4369`\r\n  - Many, many `Unexpected trienode heal packet` messages (~70% of all log lines)\r\n  - Pivot is only changed 12 times. Last one:\r\n    `WARN [09-02|16:42:58.589] Pivot seemingly stale, moving            old=7,516,913 new=7,516,977`\r\n  - Suspiciously new blocks are no longer imported: \r\n    `INFO [09-05|14:37:34.872] Imported new block headers               count=0    elapsed=15.422ms    number=7,382,818 hash=aa32c4..48c7cc age=3w4d12h    ignored=178` \r\n    - Probably because of:\r\n      `Local chain is post-merge, waiting for beacon client sync switch-over...`\r\n    - However Prsym claims geth is not synced:\r\n      `level=error msg=\"Unable to process past deposit contract logs, perhaps your execution client is not fully synced\" error=\"no contract code at given address\" prefix=powchain`\r\n- Geth `1.10.23`:\r\n  - Syncing never even starts\r\n    No sync progress is reported, apparently every peer is dropped because of:\r\n    `WARN [09-06|09:25:04.945] Snapshot extension registration failed   peer=6de3885d err=\"peer connected on snap without compatible eth support\"`\r\n\r\n#### Steps to reproduce the behaviour\r\n\r\nCompose file used:\r\n```yaml\r\nversion: \"3\"\r\n\r\nservices:\r\n  geth:\r\n    image: ethereum/client-go:v1.10.23\r\n    restart: always\r\n    network_mode: host\r\n    stop_grace_period: 1m\r\n    volumes:\r\n      - /data/geth:/data\r\n      - jwt:/jwt\r\n    command: >\r\n      --goerli\r\n      --datadir=/data\r\n      --http\r\n      --http.api eth,net,web3,txpool\r\n      --http.addr 0.0.0.0\r\n      --http.corsdomain '*'\r\n      --ws\r\n      --ws.api eth,web3,net\r\n      --authrpc.jwtsecret /jwt/jwtsecret\r\n      --authrpc.vhosts '*'\r\n      --metrics\r\n      --metrics.addr=0.0.0.0\r\n      --metrics.port=9191\r\n\r\n  prysm:\r\n    image: gcr.io/prysmaticlabs/prysm/beacon-chain:stable\r\n    restart: always\r\n    network_mode: host\r\n    volumes:\r\n      - /data/prysm:/data\r\n      - jwt:/jwt\r\n    command: >\r\n      --goerli\r\n      --datadir=/data\r\n      --rpc-host=0.0.0.0\r\n      --http-web3provider=http://localhost:8551\r\n      --jwt-secret=/jwt/jwtsecret\r\n      --accept-terms-of-use\r\n\r\nvolumes:\r\n  jwt:\r\n```\r\n",
  "closed_by": null,
  "reactions": {
    "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/25693/reactions",
    "total_count": 0,
    "+1": 0,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/25693/timeline",
  "performed_via_github_app": null,
  "state_reason": null
}
[
  {
    "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/1238079097",
    "html_url": "https://github.com/ethereum/go-ethereum/issues/25693#issuecomment-1238079097",
    "issue_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/25693",
    "id": 1238079097,
    "node_id": "IC_kwDOAOvK985Jy5Z5",
    "user": {
      "login": "fjl",
      "id": 6915,
      "node_id": "MDQ6VXNlcjY5MTU=",
      "avatar_url": "https://avatars.githubusercontent.com/u/6915?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/fjl",
      "html_url": "https://github.com/fjl",
      "followers_url": "https://api.github.com/users/fjl/followers",
      "following_url": "https://api.github.com/users/fjl/following{/other_user}",
      "gists_url": "https://api.github.com/users/fjl/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/fjl/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/fjl/subscriptions",
      "organizations_url": "https://api.github.com/users/fjl/orgs",
      "repos_url": "https://api.github.com/users/fjl/repos",
      "events_url": "https://api.github.com/users/fjl/events{/privacy}",
      "received_events_url": "https://api.github.com/users/fjl/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-09-06T12:24:50Z",
    "updated_at": "2022-09-06T12:24:50Z",
    "author_association": "MEMBER",
    "body": "> Syncing never even starts\r\n> No sync progress is reported\r\n\r\nCan you provide more information that leads you to this conclusion? It can take a while to start sometimes, just leave it running for a bit.\r\n\r\n",
    "reactions": {
      "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/1238079097/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/1238082436",
    "html_url": "https://github.com/ethereum/go-ethereum/issues/25693#issuecomment-1238082436",
    "issue_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/25693",
    "id": 1238082436,
    "node_id": "IC_kwDOAOvK985Jy6OE",
    "user": {
      "login": "rjl493456442",
      "id": 5959481,
      "node_id": "MDQ6VXNlcjU5NTk0ODE=",
      "avatar_url": "https://avatars.githubusercontent.com/u/5959481?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rjl493456442",
      "html_url": "https://github.com/rjl493456442",
      "followers_url": "https://api.github.com/users/rjl493456442/followers",
      "following_url": "https://api.github.com/users/rjl493456442/following{/other_user}",
      "gists_url": "https://api.github.com/users/rjl493456442/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/rjl493456442/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/rjl493456442/subscriptions",
      "organizations_url": "https://api.github.com/users/rjl493456442/orgs",
      "repos_url": "https://api.github.com/users/rjl493456442/repos",
      "events_url": "https://api.github.com/users/rjl493456442/events{/privacy}",
      "received_events_url": "https://api.github.com/users/rjl493456442/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-09-06T12:27:43Z",
    "updated_at": "2022-09-06T12:27:43Z",
    "author_association": "MEMBER",
    "body": "We have a couple of PRs for fixing/improving snap sync on master recently. Maybe you can try to use master once we merge this PR https://github.com/ethereum/go-ethereum/pull/25694",
    "reactions": {
      "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/1238082436/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/1238106083",
    "html_url": "https://github.com/ethereum/go-ethereum/issues/25693#issuecomment-1238106083",
    "issue_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/25693",
    "id": 1238106083,
    "node_id": "IC_kwDOAOvK985Jy__j",
    "user": {
      "login": "ulope",
      "id": 55078,
      "node_id": "MDQ6VXNlcjU1MDc4",
      "avatar_url": "https://avatars.githubusercontent.com/u/55078?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ulope",
      "html_url": "https://github.com/ulope",
      "followers_url": "https://api.github.com/users/ulope/followers",
      "following_url": "https://api.github.com/users/ulope/following{/other_user}",
      "gists_url": "https://api.github.com/users/ulope/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ulope/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ulope/subscriptions",
      "organizations_url": "https://api.github.com/users/ulope/orgs",
      "repos_url": "https://api.github.com/users/ulope/repos",
      "events_url": "https://api.github.com/users/ulope/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ulope/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-09-06T12:49:27Z",
    "updated_at": "2022-09-06T12:55:28Z",
    "author_association": "MEMBER",
    "body": "> > Syncing never even starts\r\n> > No sync progress is reported\r\n> \r\n> Can you provide more information that leads you to this conclusion? It can take a while to start sometimes, just leave it running for a bit.\r\n\r\nAre 20 hours enough? ;)\r\n\r\nThese are the top non unique log messages by count:\r\n```\r\n1776 Snapshot extension registration failed\r\n 236 Beacon client online, but never received consensus updates. Please ensure your beacon client is operational to follow the chain!\r\n  73 Dropping unsynced node during sync\r\n  28 Looking for peers\r\n  20 Regenerated local transaction journal\r\n  19 Writing clean trie cache to disk\r\n  19 Persisted the clean trie cache\r\n```\r\n\r\n\r\nI also re-tried this locally before submitting the issue (the above setup is running on a droplet).\r\n- 1.10.21 starts syncing within minutes. \r\n- 1.10.23 has been running for 15+ minutes and shows the same behaviour as on the droplet (i.e. no sync and lots of `Snapshot extension registration failed`)\r\n",
    "reactions": {
      "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/1238106083/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  }
]
