{
  "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/25802",
  "repository_url": "https://api.github.com/repos/ethereum/go-ethereum",
  "labels_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/25802/labels{/name}",
  "comments_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/25802/comments",
  "events_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/25802/events",
  "html_url": "https://github.com/ethereum/go-ethereum/issues/25802",
  "id": 1376690404,
  "node_id": "I_kwDOAOvK985SDqDk",
  "number": 25802,
  "title": "Return a reason for 403 error on AuthRPC endpoint",
  "user": {
    "login": "jakubgs",
    "id": 2212681,
    "node_id": "MDQ6VXNlcjIyMTI2ODE=",
    "avatar_url": "https://avatars.githubusercontent.com/u/2212681?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/jakubgs",
    "html_url": "https://github.com/jakubgs",
    "followers_url": "https://api.github.com/users/jakubgs/followers",
    "following_url": "https://api.github.com/users/jakubgs/following{/other_user}",
    "gists_url": "https://api.github.com/users/jakubgs/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/jakubgs/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/jakubgs/subscriptions",
    "organizations_url": "https://api.github.com/users/jakubgs/orgs",
    "repos_url": "https://api.github.com/users/jakubgs/repos",
    "events_url": "https://api.github.com/users/jakubgs/events{/privacy}",
    "received_events_url": "https://api.github.com/users/jakubgs/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [
    {
      "id": 72233650,
      "node_id": "MDU6TGFiZWw3MjIzMzY1MA==",
      "url": "https://api.github.com/repos/ethereum/go-ethereum/labels/type:bug",
      "name": "type:bug",
      "color": "FF5E5E",
      "default": false,
      "description": ""
    }
  ],
  "state": "open",
  "locked": false,
  "assignee": null,
  "assignees": [

  ],
  "milestone": null,
  "comments": 0,
  "created_at": "2022-09-17T07:04:30Z",
  "updated_at": "2022-09-17T07:05:18Z",
  "closed_at": null,
  "author_association": "NONE",
  "active_lock_reason": null,
  "body": "#### System information\r\n\r\nGeth version: `1.10.25`\r\nOS & Version: Linux\r\nCommit hash : https://github.com/ethereum/go-ethereum/commit/69568c554880b3567bace64f8848ff1be27d084d\r\n\r\n#### Expected behaviour\r\nIt would be beneficial for the sake of CL/EL node communication setup to indicate what's the actual reason for `403` HTTP error returned from an RPC or AuthRPC endpoint. My understanding is that there are at least two ways one can receive it from AuthRPC:\r\n\r\n1. Wrong hostname - the `host` header - used for request not matching `--http.vhosts`/`--authrpc.vhosts` flag value.\r\n2. Wrong JWT secret used for accessing the AuthRPC endpoint.\r\n\r\nIn the plain RPC case the second case is the only one possible as far as I know.\r\n\r\nIt would be great if Geth indicated which issue it is with either a payload or a different HTTP code.\r\nFor example `400 Bad Request` for wrong `host` header value. Or a JSON payload with an actual error message.\r\n\r\n#### Actual behaviour\r\nCurrently both errors cause a `403` error, for example:\r\n```\r\n > curl -v http://geth.example.org:8545\r\n*   Trying 10.14.0.69:8546...\r\n* Connected to geth.example.org (10.11.12.13) port 8546 (#0)\r\n> GET / HTTP/1.1\r\n> Host: geth.example.org:8545\r\n> User-Agent: curl/7.81.0\r\n> Accept: */*\r\n> \r\n* Mark bundle as not supporting multiuse\r\n< HTTP/1.1 403 Forbidden\r\n< Content-Type: text/plain; charset=utf-8\r\n< X-Content-Type-Options: nosniff\r\n< Date: Sat, 17 Sep 2022 07:00:04 GMT\r\n< Content-Length: 23\r\n* The requested URL returned error: 403\r\n* Closing connection 0\r\ncurl: (22) The requested URL returned error: 403\r\n```\r\n```\r\n > curl -v http://localhost:8545                  \r\n*   Trying 127.0.0.1:8545...\r\n* Connected to localhost (127.0.0.1) port 8545 (#0)\r\n> GET / HTTP/1.1\r\n> Host: localhost:8546\r\n> User-Agent: curl/7.81.0\r\n> Accept: */*\r\n> \r\n* Mark bundle as not supporting multiuse\r\n< HTTP/1.1 200 OK\r\n< Date: Sat, 17 Sep 2022 07:00:07 GMT\r\n< Content-Length: 0\r\n< \r\n* Connection #0 to host localhost left intact\r\n```\r\nThis can easily cause confusion since the obvious thing to blame is a wrong JWT token, but in reality it can be either or both.\r\n\r\n#### Steps to reproduce the behaviour\r\n1. Configure Geth with RPC and AuthRPC.\r\n2. Make request with wrong `vhost` value in `host` header.\r\n3. See the 403 response without payload.",
  "closed_by": null,
  "reactions": {
    "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/25802/reactions",
    "total_count": 0,
    "+1": 0,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/25802/timeline",
  "performed_via_github_app": null,
  "state_reason": null
}
[

]
