{
  "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/25887",
  "repository_url": "https://api.github.com/repos/ethereum/go-ethereum",
  "labels_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/25887/labels{/name}",
  "comments_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/25887/comments",
  "events_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/25887/events",
  "html_url": "https://github.com/ethereum/go-ethereum/issues/25887",
  "id": 1389914699,
  "node_id": "I_kwDOAOvK985S2GpL",
  "number": 25887,
  "title": "On moving all files to external Hard Drive, Geth won't start",
  "user": {
    "login": "Squee451",
    "id": 47549154,
    "node_id": "MDQ6VXNlcjQ3NTQ5MTU0",
    "avatar_url": "https://avatars.githubusercontent.com/u/47549154?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Squee451",
    "html_url": "https://github.com/Squee451",
    "followers_url": "https://api.github.com/users/Squee451/followers",
    "following_url": "https://api.github.com/users/Squee451/following{/other_user}",
    "gists_url": "https://api.github.com/users/Squee451/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Squee451/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Squee451/subscriptions",
    "organizations_url": "https://api.github.com/users/Squee451/orgs",
    "repos_url": "https://api.github.com/users/Squee451/repos",
    "events_url": "https://api.github.com/users/Squee451/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Squee451/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [

  ],
  "state": "open",
  "locked": false,
  "assignee": null,
  "assignees": [

  ],
  "milestone": null,
  "comments": 0,
  "created_at": "2022-09-28T20:34:05Z",
  "updated_at": "2022-09-28T20:34:05Z",
  "closed_at": null,
  "author_association": "NONE",
  "active_lock_reason": null,
  "body": "I have a 2 TB Sandisk Extreme SSD, and I moved all of my Prysm/Geth data to stake for Ethereum. After trying to start Geth on it, pointing to it as a data dir \r\n\r\n--geth --datadir=F:\\Ethereum --cache==1892 --http -http.api eth, net, engine, admin, --authrpc.jwtsectre ../jwt.hex\r\n\r\nAfter I do that, it completely freezes and sticks here. (see image). After 10 minutes, no progress is made. On my internal drives, it syncs fine. Any ideas?\r\n\r\n![image](https://user-images.githubusercontent.com/47549154/192882477-88183123-5cea-4df6-8a82-7f7e9bc298f0.png)\r\n",
  "closed_by": null,
  "reactions": {
    "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/25887/reactions",
    "total_count": 0,
    "+1": 0,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/25887/timeline",
  "performed_via_github_app": null,
  "state_reason": null
}
[

]
